### PR TITLE
Flutter 2 & null safety

### PR DESCRIPTION
**Pull request by guykogus**
## Summary of Changes
This also includes my changes in #179.

## Checklist
- [ ] In addition to adding the new API to Dart, I have also added its implementation to both iOS and Android.
- [ ] I have added at least 1 unit test in Dart for the new API and made sure the tests pass locally.
- [ ] I have updated [README.md](https://github.com/Instabug/Instabug-Flutter/blob/master/README.md) to add the new API.

### CODE REVIEW

**Comment by guykogus** [comment]
@AliAbdelfattah I can't get the tests to pass. It's pretty frustrating. For all the HTTP calls:
`verify(instabugCustomHttpClient.logger.onRequest(request)).called(1);`
passes, but
`verify(instabugCustomHttpClient.logger.onResponse(response, request)).called(1);`
fails. Could you please help me investigate?

**Comment by mploigt** [comment]
Too bad that nothing is happening here...

**Comment by bsameh-at-instabug** [comment]
@guykogus thank you for your contribution, this is extremely helpful, we will look into this and get back to you 👍 

@mploigt it's definitely in our backlog, we will make sure to prioritize this. I don't have an exact ETA at the moment but will let you know as soon as we have one 🙏

**Comment by via-guy** [comment]
@bsameh-at-instabug any update?

**Review by AliAbdelfattah — APPROVED** [review]

**Comment by AliAbdelfattah** [comment]
Update: this feature should be out by next week.

@guykogus thank you for your efforts in this, they're very much appreciated!

**Pull request merged**
